spring:
  application:
    name: PayTogether

  datasource:
    url: jdbc:mysql://localhost:3306/pay_together
    username: root
    password: 1234asdf
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
